# AUTOGENERATED FROM 'ls_crud/queries/delete_event.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class DeleteEventResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    address: str | None
    schedule: datetime.datetime | None
    host: DeleteEventResultHost | None


@dataclasses.dataclass
class DeleteEventResultHost(NoPydanticValidation):
    id: uuid.UUID
    name: str


async def delete_event(
    executor: edgedb.AsyncIOExecutor,
    *,
    name: str,
) -> DeleteEventResult | None:
    return await executor.query_single(
        """\
        select (
            delete Event filter .name = <str>$name
        ) {name, address, schedule, host : {name}};\
        """,
        name=name,
    )
