# AUTOGENERATED FROM 'ls_crud/queries/update_user.edgeql' WITH:
#     $ edgedb-py


from __future__ import annotations
import dataclasses
import datetime
import edgedb
import uuid


class NoPydanticValidation:
    @classmethod
    def __get_validators__(cls):
        from pydantic.dataclasses import dataclass as pydantic_dataclass
        pydantic_dataclass(cls)
        cls.__pydantic_model__.__get_validators__ = lambda: []
        return []


@dataclasses.dataclass
class UpdateUserResult(NoPydanticValidation):
    id: uuid.UUID
    name: str
    created_at: datetime.datetime


async def update_user(
    executor: edgedb.AsyncIOExecutor,
    *,
    currrent_name: str,
    new_name: str,
) -> UpdateUserResult | None:
    return await executor.query_single(
        """\
        select (
            update User filter .name = <str>$currrent_name
                set {name := <str>$new_name}
                )
                {name, created_at};\
        """,
        currrent_name=currrent_name,
        new_name=new_name,
    )
